CREATE DATABASE KISAN_MITR;

USE KISAN_MITR;

CREATE TABLE ACCOUNT (id INT NOT NULL UNIQUE AUTO_INCREMENT, name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, username VARCHAR(255) PRIMARY KEY, password VARCHAR(255) NOT NULL);

CREATE TABLE FILE_PATH (username VARCHAR(255) NOT NULL UNIQUE, file_path VARCHAR(255) NOT NULL, FOREIGN KEY (username) REFERENCES ACCOUNT(username));

CREATE TABLE IMAGE_NAME (username VARCHAR(255) NOT NULL UNIQUE, image_name VARCHAR(255), FOREIGN KEY (username) REFERENCES ACCOUNT(username));

CREATE TABLE CROP_PROPERTIES (username VARCHAR(255) NOT NULL UNIQUE, location VARCHAR(255) NOT NULL UNIQUE, crop_season VARCHAR(255) NOT NULL UNIQUE, temperature VARCHAR(255) NOT NULL UNIQUE, humidity VARCHAR(255) NOT NULL UNIQUE, rainfall VARCHAR(255) NOT NULL UNIQUE, windspeed VARCHAR(255) NOT NULL UNIQUE, crop_variety VARCHAR(255) NOT NULL UNIQUE, irrigation VARCHAR(255) NOT NULL UNIQUE, soil VARCHAR(255) NOT NULL UNIQUE, sypmtoms VARCHAR(255), FOREIGN KEY (username) REFERENCES ACCOUNT(username));

CREATE TABLE RESULT (username VARCHAR(255) NOT NULL UNIQUE, result_file VARCHAR(255) NOT NULL UNIQUE, FOREIGN KEY (username) REFERENCES ACCOUNT(username));
