CREATE DATABASE KISAN_MITR;

USE KISAN_MITR;

CREATE TABLE ACCOUNT (id INT NOT NULL UNIQUE AUTO_INCREMENT, name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, username VARCHAR(255) PRIMARY KEY, password VARCHAR(255) NOT NULL);

CREATE TABLE FILE_PATH (username VARCHAR(255) NOT NULL UNIQUE, file_path VARCHAR(255) NOT NULL, FOREIGN KEY (username) REFERENCES ACCOUNT(username));

CREATE TABLE IMAGE_NAME (image_id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) NOT NULL, image_name VARCHAR(255), FOREIGN KEY (username) REFERENCES account(username));